const mongoose = require('mongoose');
const dotenv = require('dotenv');
const Product = require('../models/Product');
const User = require('../models/User');

dotenv.config();

const products = [
  // Men's Collection
  {
    name: 'Classic Navy Blazer',
    description: 'Elegant navy blazer perfect for formal occasions and business meetings. Tailored fit with premium fabric.',
    price: 299.99,
    discount: 15,
    category: 'Men',
    subCategory: 'Jackets',
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: [{ name: 'Navy', hex: '#000080' }, { name: 'Black', hex: '#000000' }],
    images: [
      { url: 'https://images.unsplash.com/photo-1507679799987-c73779587ccf?w=600', public_id: 'blazer1' },
    ],
    stock: 50,
    featured: true,
    trending: true,
    brand: 'Aurel',
  },
  {
    name: 'Premium Cotton White Shirt',
    description: 'Classic white shirt made from 100% premium cotton. Perfect for both casual and formal wear.',
    price: 79.99,
    discount: 10,
    category: 'Men',
    subCategory: 'Shirts',
    sizes: ['S', 'M', 'L', 'XL'],
    colors: [{ name: 'White', hex: '#FFFFFF' }, { name: 'Light Blue', hex: '#ADD8E6' }],
    images: [
      { url: 'https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?w=600', public_id: 'shirt1' },
    ],
    stock: 100,
    featured: true,
    brand: 'Aurel',
  },
  {
    name: 'Slim Fit Dark Denim Jeans',
    description: 'Modern slim fit jeans with stretch denim for ultimate comfort and style.',
    price: 129.99,
    discount: 20,
    category: 'Men',
    subCategory: 'Jeans',
    sizes: ['28', '30', '32', '34', '36'],
    colors: [{ name: 'Dark Blue', hex: '#00008B' }, { name: 'Black', hex: '#000000' }],
    images: [
      { url: 'https://images.unsplash.com/photo-1542272604-787c3835535d?w=600', public_id: 'jeans1' },
    ],
    stock: 75,
    trending: true,
    brand: 'Aurel',
  },
  {
    name: 'Casual V-Neck T-Shirt',
    description: 'Comfortable cotton t-shirt with a modern v-neck design. Perfect for everyday wear.',
    price: 39.99,
    discount: 0,
    category: 'Men',
    subCategory: 'T-Shirts',
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: [
      { name: 'Black', hex: '#000000' },
      { name: 'White', hex: '#FFFFFF' },
      { name: 'Gray', hex: '#808080' },
    ],
    images: [
      { url: 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=600', public_id: 'tshirt1' },
    ],
    stock: 150,
    brand: 'Aurel',
  },
  {
    name: 'Wool Blend Trousers',
    description: 'Sophisticated trousers in wool blend fabric. Ideal for office and formal events.',
    price: 149.99,
    discount: 25,
    category: 'Men',
    subCategory: 'Trousers',
    sizes: ['30', '32', '34', '36', '38'],
    colors: [{ name: 'Charcoal', hex: '#36454F' }, { name: 'Navy', hex: '#000080' }],
    images: [
      { url: 'https://images.unsplash.com/photo-1624378439575-d8705ad7ae80?w=600', public_id: 'trousers1' },
    ],
    stock: 60,
    featured: true,
    brand: 'Aurel',
  },
  {
    name: 'Leather Oxford Shoes',
    description: 'Handcrafted leather oxford shoes with premium finish. A wardrobe essential.',
    price: 199.99,
    discount: 15,
    category: 'Men',
    subCategory: 'Shoes',
    sizes: ['7', '8', '9', '10', '11'],
    colors: [{ name: 'Brown', hex: '#8B4513' }, { name: 'Black', hex: '#000000' }],
    images: [
      { url: 'https://images.unsplash.com/photo-1614252235316-8c857d38b5f4?w=600', public_id: 'shoes1' },
    ],
    stock: 40,
    trending: true,
    brand: 'Aurel',
  },
  {
    name: 'Cashmere Sweater',
    description: 'Luxurious cashmere sweater that provides warmth and elegance.',
    price: 249.99,
    discount: 30,
    category: 'Men',
    subCategory: 'Sweaters',
    sizes: ['S', 'M', 'L', 'XL'],
    colors: [{ name: 'Beige', hex: '#F5F5DC' }, { name: 'Gray', hex: '#808080' }],
    images: [
      { url: 'https://images.unsplash.com/photo-1620799140408-edc6dcb6d633?w=600', public_id: 'sweater1' },
    ],
    stock: 35,
    featured: true,
    brand: 'Aurel',
  },
  {
    name: 'Striped Polo Shirt',
    description: 'Classic polo shirt with modern stripes. Perfect for casual outings.',
    price: 69.99,
    discount: 10,
    category: 'Men',
    subCategory: 'Shirts',
    sizes: ['S', 'M', 'L', 'XL'],
    colors: [{ name: 'Navy/White', hex: '#000080' }],
    images: [
      { url: 'https://images.unsplash.com/photo-1586790170083-2f9ceadc732d?w=600', public_id: 'polo1' },
    ],
    stock: 90,
    brand: 'Aurel',
  },
  {
    name: 'Quilted Bomber Jacket',
    description: 'Stylish bomber jacket with quilted design. Perfect for transitional weather.',
    price: 189.99,
    discount: 20,
    category: 'Men',
    subCategory: 'Jackets',
    sizes: ['M', 'L', 'XL', 'XXL'],
    colors: [{ name: 'Olive', hex: '#808000' }, { name: 'Black', hex: '#000000' }],
    images: [
      { url: 'https://images.unsplash.com/photo-1551028719-00167b16eac5?w=600', public_id: 'bomber1' },
    ],
    stock: 45,
    trending: true,
    brand: 'Aurel',
  },
  {
    name: 'Cotton Chino Shorts',
    description: 'Comfortable cotton chino shorts for summer. Available in multiple colors.',
    price: 59.99,
    discount: 15,
    category: 'Men',
    subCategory: 'Trousers',
    sizes: ['30', '32', '34', '36'],
    colors: [
      { name: 'Khaki', hex: '#C3B091' },
      { name: 'Navy', hex: '#000080' },
      { name: 'Olive', hex: '#808000' },
    ],
    images: [
      { url: 'https://images.unsplash.com/photo-1591195853828-11db59a44f6b?w=600', public_id: 'shorts1' },
    ],
    stock: 100,
    brand: 'Aurel',
  },

  // Women's Collection
  {
    name: 'Elegant Floral Maxi Dress',
    description: 'Beautiful flowing maxi dress with floral print. Perfect for summer events and parties.',
    price: 159.99,
    discount: 25,
    category: 'Women',
    subCategory: 'Dresses',
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    colors: [{ name: 'Pink', hex: '#FFC0CB' }, { name: 'Blue', hex: '#0000FF' }],
    images: [
      { url: 'https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=600', public_id: 'dress1' },
    ],
    stock: 60,
    featured: true,
    trending: true,
    brand: 'Aurel',
  },
  {
    name: 'Silk Blouse with Bow',
    description: 'Luxurious silk blouse with elegant bow detail. A wardrobe staple for professional women.',
    price: 119.99,
    discount: 15,
    category: 'Women',
    subCategory: 'Tops',
    sizes: ['XS', 'S', 'M', 'L'],
    colors: [{ name: 'Ivory', hex: '#FFFFF0' }, { name: 'Black', hex: '#000000' }],
    images: [
      { url: 'https://images.unsplash.com/photo-1564859228273-274232fdb516?w=600', public_id: 'blouse1' },
    ],
    stock: 70,
    featured: true,
    brand: 'Aurel',
  },
  {
    name: 'High-Waisted Denim Skirt',
    description: 'Trendy high-waisted denim skirt with a flattering A-line cut.',
    price: 89.99,
    discount: 20,
    category: 'Women',
    subCategory: 'Skirts',
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    colors: [{ name: 'Light Wash', hex: '#87CEEB' }, { name: 'Dark Wash', hex: '#00008B' }],
    images: [
      { url: 'https://images.unsplash.com/photo-1583496661160-fb5886a0aaaa?w=600', public_id: 'skirt1' },
    ],
    stock: 80,
    trending: true,
    brand: 'Aurel',
  },
  {
    name: 'Cashmere Cardigan',
    description: 'Soft cashmere cardigan that adds elegance to any outfit.',
    price: 199.99,
    discount: 30,
    category: 'Women',
    subCategory: 'Sweaters',
    sizes: ['S', 'M', 'L', 'XL'],
    colors: [{ name: 'Cream', hex: '#FFFDD0' }, { name: 'Rose', hex: '#FF007F' }],
    images: [
      { url: 'https://images.unsplash.com/photo-1591369822096-ffd140ec948f?w=600', public_id: 'cardigan1' },
    ],
    stock: 50,
    featured: true,
    brand: 'Aurel',
  },
  {
    name: 'Pleated Midi Skirt',
    description: 'Elegant pleated midi skirt that flows beautifully. Versatile piece for any season.',
    price: 109.99,
    discount: 15,
    category: 'Women',
    subCategory: 'Skirts',
    sizes: ['XS', 'S', 'M', 'L'],
    colors: [{ name: 'Burgundy', hex: '#800020' }, { name: 'Navy', hex: '#000080' }],
    images: [
      { url: 'https://images.unsplash.com/photo-1562137369-1a1a0bc66744?w=600', public_id: 'skirt2' },
    ],
    stock: 65,
    trending: true,
    brand: 'Aurel',
  },
  {
    name: 'Wrap Dress in Jersey',
    description: 'Flattering wrap dress in soft jersey fabric. Comfortable and stylish.',
    price: 139.99,
    discount: 25,
    category: 'Women',
    subCategory: 'Dresses',
    sizes: ['S', 'M', 'L', 'XL'],
    colors: [{ name: 'Black', hex: '#000000' }, { name: 'Emerald', hex: '#50C878' }],
    images: [
      { url: 'https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?w=600', public_id: 'dress2' },
    ],
    stock: 55,
    featured: true,
    brand: 'Aurel',
  },
  {
    name: 'Linen Wide-Leg Trousers',
    description: 'Breezy linen trousers with wide-leg cut. Perfect for summer.',
    price: 99.99,
    discount: 10,
    category: 'Women',
    subCategory: 'Trousers',
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    colors: [{ name: 'White', hex: '#FFFFFF' }, { name: 'Beige', hex: '#F5F5DC' }],
    images: [
      { url: 'https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?w=600', public_id: 'trousers2' },
    ],
    stock: 75,
    brand: 'Aurel',
  },
  {
    name: 'Embroidered Tunic Top',
    description: 'Beautiful tunic top with intricate embroidery. Bohemian chic style.',
    price: 89.99,
    discount: 20,
    category: 'Women',
    subCategory: 'Tops',
    sizes: ['S', 'M', 'L', 'XL'],
    colors: [{ name: 'White', hex: '#FFFFFF' }, { name: 'Coral', hex: '#FF7F50' }],
    images: [
      { url: 'https://images.unsplash.com/photo-1624206112431-23f4db892d4a?w=600', public_id: 'tunic1' },
    ],
    stock: 60,
    trending: true,
    brand: 'Aurel',
  },
  {
    name: 'Leather Biker Jacket',
    description: 'Edgy leather biker jacket that adds attitude to any outfit.',
    price: 349.99,
    discount: 35,
    category: 'Women',
    subCategory: 'Jackets',
    sizes: ['XS', 'S', 'M', 'L'],
    colors: [{ name: 'Black', hex: '#000000' }],
    images: [
      { url: 'https://images.unsplash.com/photo-1551028719-00167b16eac5?w=600', public_id: 'jacket1' },
    ],
    stock: 40,
    featured: true,
    brand: 'Aurel',
  },
  {
    name: 'Knit Sweater Dress',
    description: 'Cozy knit sweater dress perfect for fall and winter. Comfortable and chic.',
    price: 129.99,
    discount: 20,
    category: 'Women',
    subCategory: 'Dresses',
    sizes: ['S', 'M', 'L', 'XL'],
    colors: [{ name: 'Camel', hex: '#C19A6B' }, { name: 'Gray', hex: '#808080' }],
    images: [
      { url: 'https://images.unsplash.com/photo-1515372039744-b8f02a3ae446?w=600', public_id: 'dress3' },
    ],
    stock: 50,
    trending: true,
    brand: 'Aurel',
  },
  {
    name: 'Satin Camisole',
    description: 'Delicate satin camisole that can be dressed up or down.',
    price: 59.99,
    discount: 15,
    category: 'Women',
    subCategory: 'Tops',
    sizes: ['XS', 'S', 'M', 'L'],
    colors: [
      { name: 'Champagne', hex: '#F7E7CE' },
      { name: 'Black', hex: '#000000' },
      { name: 'Blush', hex: '#DE5D83' },
    ],
    images: [
      { url: 'https://images.unsplash.com/photo-1618932260643-eee4a2f652a6?w=600', public_id: 'cami1' },
    ],
    stock: 90,
    brand: 'Aurel',
  },
  {
    name: 'Tailored Wool Coat',
    description: 'Classic tailored coat in premium wool. Timeless winter essential.',
    price: 399.99,
    discount: 40,
    category: 'Women',
    subCategory: 'Jackets',
    sizes: ['S', 'M', 'L', 'XL'],
    colors: [{ name: 'Camel', hex: '#C19A6B' }, { name: 'Black', hex: '#000000' }],
    images: [
      { url: 'https://images.unsplash.com/photo-1539533018447-63fcce2678e3?w=600', public_id: 'coat1' },
    ],
    stock: 30,
    featured: true,
    brand: 'Aurel',
  },

  // Accessories
  {
    name: 'Luxury Leather Handbag',
    description: 'Premium leather handbag with gold hardware. Spacious and elegant.',
    price: 349.99,
    discount: 25,
    category: 'Accessories',
    subCategory: 'Bags',
    sizes: ['One Size'],
    colors: [{ name: 'Black', hex: '#000000' }, { name: 'Tan', hex: '#D2B48C' }],
    images: [
      { url: 'https://images.unsplash.com/photo-1584917865442-de89df76afd3?w=600', public_id: 'bag1' },
    ],
    stock: 45,
    featured: true,
    trending: true,
    brand: 'Aurel',
  },
  {
    name: 'Classic Aviator Sunglasses',
    description: 'Timeless aviator sunglasses with UV protection. A must-have accessory.',
    price: 149.99,
    discount: 20,
    category: 'Accessories',
    subCategory: 'Sunglasses',
    sizes: ['One Size'],
    colors: [{ name: 'Gold/Brown', hex: '#DAA520' }, { name: 'Silver/Gray', hex: '#C0C0C0' }],
    images: [
      { url: 'https://images.unsplash.com/photo-1511499767150-a48a237f0083?w=600', public_id: 'sunglasses1' },
    ],
    stock: 100,
    trending: true,
    brand: 'Aurel',
  },
  {
    name: 'Minimalist Watch',
    description: 'Elegant minimalist watch with leather strap. Perfect for any occasion.',
    price: 249.99,
    discount: 30,
    category: 'Accessories',
    subCategory: 'Watches',
    sizes: ['One Size'],
    colors: [{ name: 'Silver/Black', hex: '#000000' }, { name: 'Gold/Brown', hex: '#8B4513' }],
    images: [
      { url: 'https://images.unsplash.com/photo-1524592094714-0f0654e20314?w=600', public_id: 'watch1' },
    ],
    stock: 60,
    featured: true,
    brand: 'Aurel',
  },
  {
    name: 'Gold Chain Necklace',
    description: 'Delicate gold chain necklace. Versatile piece that complements any outfit.',
    price: 89.99,
    discount: 15,
    category: 'Accessories',
    subCategory: 'Jewelry',
    sizes: ['One Size'],
    colors: [{ name: 'Gold', hex: '#FFD700' }],
    images: [
      { url: 'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=600', public_id: 'necklace1' },
    ],
    stock: 80,
    trending: true,
    brand: 'Aurel',
  },
  {
    name: 'Cashmere Scarf',
    description: 'Luxurious cashmere scarf in various colors. Soft and warm.',
    price: 129.99,
    discount: 20,
    category: 'Accessories',
    subCategory: 'Bags',
    sizes: ['One Size'],
    colors: [
      { name: 'Camel', hex: '#C19A6B' },
      { name: 'Gray', hex: '#808080' },
      { name: 'Navy', hex: '#000080' },
    ],
    images: [
      { url: 'https://images.unsplash.com/photo-1601924994987-69e26d50dc26?w=600', public_id: 'scarf1' },
    ],
    stock: 70,
    brand: 'Aurel',
  },
  {
    name: 'Leather Card Holder',
    description: 'Slim leather card holder with multiple slots. Compact and stylish.',
    price: 49.99,
    discount: 10,
    category: 'Accessories',
    subCategory: 'Bags',
    sizes: ['One Size'],
    colors: [{ name: 'Black', hex: '#000000' }, { name: 'Brown', hex: '#8B4513' }],
    images: [
      { url: 'https://images.unsplash.com/photo-1627123424574-724758594e93?w=600', public_id: 'cardholder1' },
    ],
    stock: 120,
    brand: 'Aurel',
  },
  {
    name: 'Statement Earrings',
    description: 'Bold statement earrings that add drama to any look.',
    price: 79.99,
    discount: 25,
    category: 'Accessories',
    subCategory: 'Jewelry',
    sizes: ['One Size'],
    colors: [{ name: 'Gold', hex: '#FFD700' }, { name: 'Silver', hex: '#C0C0C0' }],
    images: [
      { url: 'https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?w=600', public_id: 'earrings1' },
    ],
    stock: 90,
    featured: true,
    brand: 'Aurel',
  },
  {
    name: 'Canvas Tote Bag',
    description: 'Eco-friendly canvas tote bag. Perfect for everyday use.',
    price: 39.99,
    discount: 0,
    category: 'Accessories',
    subCategory: 'Bags',
    sizes: ['One Size'],
    colors: [{ name: 'Natural', hex: '#F5F5DC' }, { name: 'Black', hex: '#000000' }],
    images: [
      { url: 'https://images.unsplash.com/photo-1590874103328-eac38a683ce7?w=600', public_id: 'tote1' },
    ],
    stock: 150,
    brand: 'Aurel',
  },
  {
    name: 'Polarized Sport Sunglasses',
    description: 'High-performance polarized sunglasses for outdoor activities.',
    price: 119.99,
    discount: 15,
    category: 'Accessories',
    subCategory: 'Sunglasses',
    sizes: ['One Size'],
    colors: [{ name: 'Black', hex: '#000000' }, { name: 'Blue', hex: '#0000FF' }],
    images: [
      { url: 'https://images.unsplash.com/photo-1572635196237-14b3f281503f?w=600', public_id: 'sunglasses2' },
    ],
    stock: 75,
    brand: 'Aurel',
  },
  {
    name: 'Pearl Bracelet',
    description: 'Elegant pearl bracelet with adjustable clasp. Timeless accessory.',
    price: 159.99,
    discount: 20,
    category: 'Accessories',
    subCategory: 'Jewelry',
    sizes: ['One Size'],
    colors: [{ name: 'White', hex: '#FFFFFF' }],
    images: [
      { url: 'https://images.unsplash.com/photo-1611591437281-460bfbe1220a?w=600', public_id: 'bracelet1' },
    ],
    stock: 50,
    trending: true,
    brand: 'Aurel',
  },

  // Additional Products to reach 50+
  {
    name: 'Performance Running Shoes',
    description: 'Lightweight running shoes with superior cushioning and support.',
    price: 159.99,
    discount: 25,
    category: 'Men',
    subCategory: 'Shoes',
    sizes: ['7', '8', '9', '10', '11', '12'],
    colors: [{ name: 'Black/Red', hex: '#000000' }, { name: 'Gray/Blue', hex: '#808080' }],
    images: [
      { url: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600', public_id: 'shoes2' },
    ],
    stock: 85,
    trending: true,
    brand: 'Aurel',
  },
  {
    name: 'Quilted Crossbody Bag',
    description: 'Chic quilted crossbody bag with chain strap. Perfect evening accessory.',
    price: 199.99,
    discount: 30,
    category: 'Accessories',
    subCategory: 'Bags',
    sizes: ['One Size'],
    colors: [{ name: 'Black', hex: '#000000' }, { name: 'Red', hex: '#FF0000' }],
    images: [
      { url: 'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=600', public_id: 'bag2' },
    ],
    stock: 55,
    featured: true,
    brand: 'Aurel',
  },
  {
    name: 'Hooded Parka Jacket',
    description: 'Warm parka with faux fur hood. Perfect for cold weather.',
    price: 279.99,
    discount: 35,
    category: 'Women',
    subCategory: 'Jackets',
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    colors: [{ name: 'Olive', hex: '#808000' }, { name: 'Black', hex: '#000000' }],
    images: [
      { url: 'https://images.unsplash.com/photo-1539533018447-63fcce2678e3?w=600', public_id: 'parka1' },
    ],
    stock: 40,
    brand: 'Aurel',
  },
  {
    name: 'Athletic Track Pants',
    description: 'Comfortable track pants with tapered fit. Great for workouts and casual wear.',
    price: 69.99,
    discount: 15,
    category: 'Men',
    subCategory: 'Trousers',
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: [{ name: 'Black', hex: '#000000' }, { name: 'Navy', hex: '#000080' }],
    images: [
      { url: 'https://images.unsplash.com/photo-1506629082955-511b1aa562c8?w=600', public_id: 'trackpants1' },
    ],
    stock: 100,
    brand: 'Aurel',
  },
  {
    name: 'Satin Slip Dress',
    description: 'Luxurious satin slip dress with adjustable straps. Perfect for special occasions.',
    price: 179.99,
    discount: 25,
    category: 'Women',
    subCategory: 'Dresses',
    sizes: ['XS', 'S', 'M', 'L'],
    colors: [{ name: 'Champagne', hex: '#F7E7CE' }, { name: 'Black', hex: '#000000' }],
    images: [
      { url: 'https://images.unsplash.com/photo-1566174053879-31528523f8ae?w=600', public_id: 'slip1' },
    ],
    stock: 45,
    featured: true,
    trending: true,
    brand: 'Aurel',
  },
  {
    name: 'Denim Jacket',
    description: 'Classic denim jacket with vintage wash. A timeless wardrobe staple.',
    price: 119.99,
    discount: 20,
    category: 'Men',
    subCategory: 'Jackets',
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: [{ name: 'Light Wash', hex: '#87CEEB' }, { name: 'Dark Wash', hex: '#00008B' }],
    images: [
      { url: 'https://images.unsplash.com/photo-1576995853123-5a10305d93c0?w=600', public_id: 'denim1' },
    ],
    stock: 70,
    trending: true,
    brand: 'Aurel',
  },
  {
    name: 'Oversized Sunglasses',
    description: 'Fashion-forward oversized sunglasses with gradient lenses.',
    price: 99.99,
    discount: 15,
    category: 'Accessories',
    subCategory: 'Sunglasses',
    sizes: ['One Size'],
    colors: [{ name: 'Black/Gray', hex: '#000000' }, { name: 'Tortoise', hex: '#8B4513' }],
    images: [
      { url: 'https://images.unsplash.com/photo-1577803645773-f96470509666?w=600', public_id: 'sunglasses3' },
    ],
    stock: 80,
    brand: 'Aurel',
  },
  {
    name: 'Stainless Steel Watch',
    description: 'Modern stainless steel watch with chronograph features.',
    price: 299.99,
    discount: 35,
    category: 'Accessories',
    subCategory: 'Watches',
    sizes: ['One Size'],
    colors: [{ name: 'Silver', hex: '#C0C0C0' }, { name: 'Black', hex: '#000000' }],
    images: [
      { url: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=600', public_id: 'watch2' },
    ],
    stock: 50,
    featured: true,
    brand: 'Aurel',
  },
  {
    name: 'Layered Gold Necklace Set',
    description: 'Trendy layered necklace set with multiple chains. Instant style upgrade.',
    price: 119.99,
    discount: 20,
    category: 'Accessories',
    subCategory: 'Jewelry',
    sizes: ['One Size'],
    colors: [{ name: 'Gold', hex: '#FFD700' }],
    images: [
      { url: 'https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?w=600', public_id: 'necklace2' },
    ],
    stock: 65,
    trending: true,
    brand: 'Aurel',
  },
  {
    name: 'Suede Ankle Boots',
    description: 'Stylish suede ankle boots with block heel. Perfect for fall.',
    price: 189.99,
    discount: 25,
    category: 'Women',
    subCategory: 'Shoes',
    sizes: ['6', '7', '8', '9', '10'],
    colors: [{ name: 'Tan', hex: '#D2B48C' }, { name: 'Black', hex: '#000000' }],
    images: [
      { url: 'https://images.unsplash.com/photo-1543163521-1bf539c55dd2?w=600', public_id: 'boots1' },
    ],
    stock: 55,
    featured: true,
    brand: 'Aurel',
  },
  {
    name: 'Printed Silk Scarf',
    description: 'Luxurious silk scarf with artistic print. Versatile styling piece.',
    price: 89.99,
    discount: 15,
    category: 'Accessories',
    subCategory: 'Bags',
    sizes: ['One Size'],
    colors: [{ name: 'Multi', hex: '#000000' }],
    images: [
      { url: 'https://images.unsplash.com/photo-1601924994987-69e26d50dc26?w=600', public_id: 'scarf2' },
    ],
    stock: 70,
    brand: 'Aurel',
  },
  {
    name: 'Henley Long Sleeve Shirt',
    description: 'Casual henley shirt perfect for layering. Comfortable cotton blend.',
    price: 49.99,
    discount: 10,
    category: 'Men',
    subCategory: 'Shirts',
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: [
      { name: 'Gray', hex: '#808080' },
      { name: 'Navy', hex: '#000080' },
      { name: 'Burgundy', hex: '#800020' },
    ],
    images: [
      { url: 'https://images.unsplash.com/photo-1602810320073-1230c46d89b4?w=600', public_id: 'henley1' },
    ],
    stock: 95,
    brand: 'Aurel',
  },
  {
    name: 'Ruffled Blouse',
    description: 'Romantic blouse with ruffled details. Feminine and elegant.',
    price: 79.99,
    discount: 20,
    category: 'Women',
    subCategory: 'Tops',
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    colors: [{ name: 'White', hex: '#FFFFFF' }, { name: 'Blush', hex: '#DE5D83' }],
    images: [
      { url: 'https://images.unsplash.com/photo-1618932260643-eee4a2f652a6?w=600', public_id: 'blouse2' },
    ],
    stock: 60,
    trending: true,
    brand: 'Aurel',
  },
  {
    name: 'Cargo Utility Pants',
    description: 'Functional cargo pants with multiple pockets. Street style essential.',
    price: 99.99,
    discount: 15,
    category: 'Men',
    subCategory: 'Trousers',
    sizes: ['30', '32', '34', '36', '38'],
    colors: [{ name: 'Khaki', hex: '#C3B091' }, { name: 'Black', hex: '#000000' }],
    images: [
      { url: 'https://images.unsplash.com/photo-1624378439575-d8705ad7ae80?w=600', public_id: 'cargo1' },
    ],
    stock: 75,
    brand: 'Aurel',
  },
  {
    name: 'Cropped Sweater',
    description: 'Trendy cropped sweater in soft knit. Perfect for high-waisted bottoms.',
    price: 69.99,
    discount: 20,
    category: 'Women',
    subCategory: 'Sweaters',
    sizes: ['XS', 'S', 'M', 'L'],
    colors: [{ name: 'White', hex: '#FFFFFF' }, { name: 'Pink', hex: '#FFC0CB' }],
    images: [
      { url: 'https://images.unsplash.com/photo-1434389677669-e08b4cac3105?w=600', public_id: 'sweater2' },
    ],
    stock: 80,
    trending: true,
    brand: 'Aurel',
  },
];

const admin = {
  firstName: 'Admin',
  lastName: 'User',
  email: 'admin@aurel.com',
  password: 'Admin@123',
  role: 'admin',
  phone: '9827193800',
  country: 'USA',
};

const seedDatabase = async () => {
  try {
    await mongoose.connect(process.env.MONGODB_URI, {
      useNewUrlParser: true,
      useUnifiedTopology: true,
    });

    console.log('Connected to MongoDB');

    // Clear existing data
    await Product.deleteMany({});
    await User.deleteMany({});

    console.log('Cleared existing data');

    // Insert products
    await Product.insertMany(products);
    console.log(`✅ ${products.length} products seeded successfully`);

    // Insert admin user
    await User.create(admin);
    console.log('✅ Admin user created successfully');

    console.log('🎉 Database seeded successfully!');
    process.exit(0);
  } catch (error) {
    console.error('❌ Error seeding database:', error);
    process.exit(1);
  }
};

seedDatabase();
